name: macos-latest

on:
  push:
    branches:
      - "main"

jobs:
  macos-latest:
    runs-on: macos-latest
    steps:
      - name: some checks
        run: |
          env
          alias
          python3 --version
          gcc-12 -v
          cmake --version
          git -v
          brew install pcre

