name: macos-latest

on:
  push:
    branches:
      - "main"

jobs:
  macos-latest:
    runs-on: macos-latest
    steps:
      - name: some checks
        run: |
          env
          which python3
          which gcc
          which cmake
